
const { createClient } = require('@sanity/client')
require('dotenv').config({ path: require('path').join(__dirname, '..', '.env.local') })

const client = createClient({ projectId: '0j4eqnmw', dataset: 'production', token: process.env.SANITY_TOKEN, apiVersion: '2024-01-01', useCdn: false })

// Manual cuisine fixes
const FIXES = {
  'Aunts et Uncles': 'Vegan',
  'Brooklyn Dumpling Shop - Midtown': 'Dumplings',
  'Brooklyn Dumpling Shop - UES': 'Dumplings',
  'Mesob Restaurant': 'Ethiopian',
  'TONG': 'Thai',
  'Sigri': 'Sri Lankan',
  '5ive Spice LES': 'Vietnamese',
  'Zara Mediterranean Grill': 'Mediterranean',
  'Panzón': 'Mexican',
  'Namkeen - Chatham': 'Indian',
  'Namkeen - Brooklyn': 'Indian',
  'Namkeen - Metuchen': 'Indian',
  'Namkeen - Lake Hiawatha': 'Indian',
  'Zutto Japanese American Bar': 'Japanese',
  'General Tso\'s': 'Chinese',
  'Lechon Loco': 'Filipino',
  'ROOH Palo Alto': 'Indian',
  'Kalamaki Greek La': 'Greek',
  'eléa': 'Greek',
  'Kipos Greek': 'Greek',
  'Bunny Chow - South African Food - Miramar Shebeen': 'South African',
  'Bunny Chow - South African Food - North Park Shebeen': 'South African',
  'Smögen Appetizers': 'Scandinavian',
  'Habana Cuba Restaurant': 'Cuban',
  'Memphis Seoul': 'Korean-American',
  'Taqueria Al Pastor - Bushwick': 'Mexican',
  'Taqueria Nixtamal': 'Mexican',
  'Trejo\'s Tacos': 'Mexican',
  'Hugo\'s Tacos Studio City': 'Mexican',
  'Hugo\'s Tacos Atwater Village': 'Mexican',
  'El Burro': 'Mexican',
  'El Xolo Tacos': 'Mexican',
  'El Gallo Taqueria': 'Mexican',
  'Chicas Tacos - Miracle Mile': 'Mexican',
  'Local Smoke BBQ - Red Bank': 'BBQ',
  'Local Smoke BBQ - Cookstown': 'BBQ',
  'Local Smoke BBQ - Neptune City': 'BBQ',
  'Local Smoke BBQ - Sea Girt': 'BBQ',
  'Local Pig': 'BBQ',
  'Bobby U\'s BBQ': 'BBQ',
  'Yeah Buddy Barbecue': 'BBQ',
  'Huckaby\'s Smokehouse': 'BBQ',
  'Westwoods BBQ & Spice Co.': 'BBQ',
  'Ramen Lab Eatery - West Boca Raton': 'Ramen',
  'Sushi Dojo': 'Japanese',
  'oomi kitchen': 'Korean',
  'Moonburger Brooklyn': 'Burgers',
  'Feed Co. Burgers': 'Burgers',
  '206 Burger Company': 'Burgers',
  'Woo Woo Burgers - Chandler': 'Burgers',
  'Woo Woo Burgers - Kyle': 'Burgers',
  'Woo Woo Burgers - Avery Ranch': 'Burgers',
  'Woo Woo Burgers - Scottsdale': 'Burgers',
  'Taim - City Spire': 'Mediterranean',
  'Taim - FIDI': 'Mediterranean',
  'Taim - Nolita': 'Mediterranean',
  'Taim - Broadway': 'Mediterranean',
  'Taim - West Village': 'Mediterranean',
  'Taim - Hoyt': 'Mediterranean',
  'Taim - Park Slope': 'Mediterranean',
  'Taim - Plainview': 'Mediterranean',
  'Taim - Fresh Meadows, Queens': 'Mediterranean',
  'Taim - LIC / JACX&CO': 'Mediterranean',
  'Taim - Dupont Circle': 'Mediterranean',
  'Fish Cheeks': 'Thai',
  'Miss Ada': 'Mediterranean',
  'Strange Delight': 'Seafood',
  'Point Lobster Co': 'Seafood',
  '2nd Jetty Seafood': 'Seafood',
  'Sandy Hook Seafood': 'Seafood',
  'Pismo Fish and Chips': 'Seafood',
  'Shuk': 'Middle Eastern',
  'Teranga': 'West African',
  'Veselka': 'Ukrainian',
  'East Wind Snack Shop': 'Dumplings',
  'Binge Biryani - Long Island City': 'Indian',
  'Tikka Bowls and Tacos - Tapestry Park': 'Indian',
  'Zunkaa Authentic Indian Cuisine': 'Indian',
  'Rice N Spice': 'Indian',
  'TROPICALI Brazilian Kitchen': 'Brazilian',
  'Pine and Crane DTLA': 'Taiwanese',
  'Wing Dome - Waterfront': 'Wings',
  'Wing Dome - Kirkland': 'Wings',
  'Chook - Platt Park': 'Australian',
  'Chook - 8th Ave & Birch St': 'Australian',
  'Chook - Cherry Hills Marketplace': 'Australian',
  'Donna Jean - San Diego': 'Vegan',
  'Donna Jean - Los Angeles': 'Vegan',
  'Plant Life Vegan Catering': 'Vegan',
  'Luna Verde Vegan Mexican Restaurant': 'Vegan Mexican',
  'Maciel\'s Plant-Based Butcher & Deli': 'Vegan',
  'La Sandwicherie - Chelsea': 'French',
  'La Sandwicherie - Upper East Side': 'French',
  'Colette\'s Creations': 'French',
  'Firenze: Italian Street Food': 'Italian',
  'Botte - Brooklyn': 'Italian',
  'Botte - Astoria': 'Italian',
  'Botte - UES': 'Italian',
  'Francesca Catering - Glen Rock': 'Italian',
  'Francesca Catering - Elmwood Park': 'Italian',
  'Pelons Tex Mex': 'Tex-Mex',
  'Z\'Tejas - Kyle': 'Tex-Mex',
  'Z\'Tejas - Avery Ranch': 'Tex-Mex',
  'Z\'Tejas - Scottsdale': 'Tex-Mex',
  'Z\'Tejas - Chandler': 'Tex-Mex',
  'De Nada': 'Mexican',
  'Surf Taco - Point Pleasant': 'Mexican',
  'Surf Taco - Long Branch': 'Mexican',
  'Surf Taco - Red Bank': 'Mexican',
  'Surf Taco - Lacey': 'Mexican',
  'Surf Taco - Manasquan': 'Mexican',
  'Surf Taco - Silverton': 'Mexican',
  'Surf Taco - Wall': 'Mexican',
}

async function main() {
  const all = await client.fetch('*[_type == "restaurant"]{_id, name, cuisine}')
  console.log('Total restaurants: ' + all.length)
  let updated = 0

  for (const r of all) {
    const fix = FIXES[r.name]
    if (fix && fix !== r.cuisine) {
      await client.patch(r._id).set({ cuisine: fix }).commit()
      console.log('Fixed: ' + r.name + ' | ' + r.cuisine + ' -> ' + fix)
      updated++
    }
  }
  console.log('\nDone! Updated: ' + updated)
}
main()
